# Server
server.port=8081

# Datasource: set these environment variables on your host (do NOT commit secrets)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d423akbipnbc73c0ijag-a.oregon-postgres.render.com:5432/myapp_db_0k76?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myapp_db_0k76_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:I7mNgmN3ESTawc8MINK9HpDzn5huF7xs}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hikari
spring.datasource.hikari.maximum-pool-size=10

# --- EMAIL CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gobinathjobs@gmail.com
spring.mail.password=udmu jxyw opav dnox
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true