# Azure PostgreSQL connection
spring.datasource.url=jdbc:postgresql://chatee.postgres.database.azure.com:5432/user-dev?sslmode=require
spring.datasource.username=gobi@chatee
spring.datasource.password=Raja123@

# PostgreSQL Driver & JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
